### ISSUE TITLE
Breaking refactoring upstream. 

### ISSUE THREAD

**Issue by pysan3** [andreadev-it/neorg-module-tutorials#1]
Hi @andreadev-it, thanks for the awesome tutorial. 

Due to the refactoring done in https://github.com/nvim-neorg/neorg/pull/1001, the code in this tutorial seems to be outdated. 

Especially `neorg` variable is no more a global variable, making `neorg.modules.create(…)` access `nil`. 

It’d be nice if you could update the tutorials. 

Thank you in advance.

**Comment by andreadev-it** [comment]
Thanks @pysan3 for the heads-up! I'm gonna update the tutorials as soon as possible 👍🏼

**Comment by andreadev-it** [comment]
Fixed in   899e780531661cead4ded53e8d72d0cabb45becb

**Comment by pysan3** [comment]
What a quick fix! Thanks!
